{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "links": {"attachments": {"href": "data/repositories/osrf/gzweb/issues/160/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gzweb/issues/160.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/160/watch"}, "comments": {"href": "data/repositories/osrf/gzweb/issues/160/comments_page=1.json"}, "html": {"href": "#!/osrf/gzweb/issues/160/deploysh-does-not-handle-spaces-in-model"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/160/vote"}}, "reporter": {"display_name": "Will Baker", "uuid": "{29059f61-e8ef-4122-a6c9-ebf4207e716a}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B29059f61-e8ef-4122-a6c9-ebf4207e716a%7D"}, "html": {"href": "https://bitbucket.org/%7B29059f61-e8ef-4122-a6c9-ebf4207e716a%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1ef1c401594173d16b47bc3b10e3dc75d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsWB-5.png"}}, "nickname": "William Baker", "type": "user", "account_id": "557058:8aa0b9c9-7cec-46ea-9d87-86b91c48c7a6"}, "title": "deploy.sh does not handle spaces in model filenames", "component": null, "votes": 0, "watches": 1, "content": {"raw": "```\r\n#!bash\r\n\r\n['sed', '-i', '-e', 's/\\\\(\\\\.tga\\\\|\\\\.tiff\\\\|\\\\.tif\\\\|\\\\.jpg\\\\|\\\\.jpeg\\\\|\\\\.gif\\\\)/\\\\.png/g', 'Male.dae']\r\nsed: can't read Male.dae: No such file or directory\r\nerror Command '['sed', '-i', '-e', 's/\\\\(\\\\.tga\\\\|\\\\.tiff\\\\|\\\\.tif\\\\|\\\\.jpg\\\\|\\\\.jpeg\\\\|\\\\.gif\\\\)/\\\\.png/g', 'Male.dae']' returned non-zero exit status 2\r\nTraceback (most recent call last):\r\n  File \"./webify_models_v2.py\", line 67, in <module>\r\n    subprocess.check_call(sed_cmd)\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 190, in check_call\r\n    raise CalledProcessError(retcode, cmd)\r\nsubprocess.CalledProcessError: Command '['sed', '-i', '-e', 's/\\\\(\\\\.tga\\\\|\\\\.tiff\\\\|\\\\.tif\\\\|\\\\.jpg\\\\|\\\\.jpeg\\\\|\\\\.gif\\\\)/\\\\.png/g', 'Male.dae']' returned non-zero exit status 2\r\n\r\n```\r\n\r\nAdded a model that is named `Large Male`\r\n\r\n\r\n```\r\n#!bash\r\n'Large Male'\r\n\u251c\u2500\u2500 materials\r\n\u2502\u00a0\u00a0 \u2514\u2500\u2500 textures\r\n\u2502\u00a0\u00a0     \u2514\u2500\u2500 Large Male.png\r\n\u251c\u2500\u2500 meshes\r\n\u2502\u00a0\u00a0 \u2514\u2500\u2500 Large Male.dae\r\n\u251c\u2500\u2500 model.config\r\n\u2514\u2500\u2500 model.sdf\r\n```\r\n\r\ngazebo 9.4.1\r\nGzweb on branch insert_sdf\r\nusing docker file from issue #158\r\nand pull request #173\r\n#!/osrf/gzweb/pull-requests/173", "markup": "markdown", "html": "<div class=\"codehilite language-bash\"><pre><span></span><span class=\"o\">[</span><span class=\"s1\">&#39;sed&#39;</span>, <span class=\"s1\">&#39;-i&#39;</span>, <span class=\"s1\">&#39;-e&#39;</span>, <span class=\"s1\">&#39;s/\\\\(\\\\.tga\\\\|\\\\.tiff\\\\|\\\\.tif\\\\|\\\\.jpg\\\\|\\\\.jpeg\\\\|\\\\.gif\\\\)/\\\\.png/g&#39;</span>, <span class=\"s1\">&#39;Male.dae&#39;</span><span class=\"o\">]</span>\nsed: can<span class=\"s1\">&#39;t read Male.dae: No such file or directory</span>\n<span class=\"s1\">error Command &#39;</span><span class=\"o\">[</span><span class=\"s1\">&#39;sed&#39;</span>, <span class=\"s1\">&#39;-i&#39;</span>, <span class=\"s1\">&#39;-e&#39;</span>, <span class=\"s1\">&#39;s/\\\\(\\\\.tga\\\\|\\\\.tiff\\\\|\\\\.tif\\\\|\\\\.jpg\\\\|\\\\.jpeg\\\\|\\\\.gif\\\\)/\\\\.png/g&#39;</span>, <span class=\"s1\">&#39;Male.dae&#39;</span><span class=\"o\">]</span><span class=\"s1\">&#39; returned non-zero exit status 2</span>\n<span class=\"s1\">Traceback (most recent call last):</span>\n<span class=\"s1\">  File &quot;./webify_models_v2.py&quot;, line 67, in &lt;module&gt;</span>\n<span class=\"s1\">    subprocess.check_call(sed_cmd)</span>\n<span class=\"s1\">  File &quot;/usr/lib/python2.7/subprocess.py&quot;, line 190, in check_call</span>\n<span class=\"s1\">    raise CalledProcessError(retcode, cmd)</span>\n<span class=\"s1\">subprocess.CalledProcessError: Command &#39;</span><span class=\"o\">[</span><span class=\"s1\">&#39;sed&#39;</span>, <span class=\"s1\">&#39;-i&#39;</span>, <span class=\"s1\">&#39;-e&#39;</span>, <span class=\"s1\">&#39;s/\\\\(\\\\.tga\\\\|\\\\.tiff\\\\|\\\\.tif\\\\|\\\\.jpg\\\\|\\\\.jpeg\\\\|\\\\.gif\\\\)/\\\\.png/g&#39;</span>, <span class=\"s1\">&#39;Male.dae&#39;</span><span class=\"o\">]</span><span class=\"err\">&#39;</span> returned non-zero <span class=\"nb\">exit</span> status <span class=\"m\">2</span>\n</pre></div>\n\n\n<p>Added a model that is named <code>Large Male</code></p>\n<div class=\"codehilite language-bash\"><pre><span></span><span class=\"s1\">&#39;Large Male&#39;</span>\n\u251c\u2500\u2500 materials\n\u2502\u00a0\u00a0 \u2514\u2500\u2500 textures\n\u2502\u00a0\u00a0     \u2514\u2500\u2500 Large Male.png\n\u251c\u2500\u2500 meshes\n\u2502\u00a0\u00a0 \u2514\u2500\u2500 Large Male.dae\n\u251c\u2500\u2500 model.config\n\u2514\u2500\u2500 model.sdf\n</pre></div>\n\n\n<p>gazebo 9.4.1\nGzweb on branch insert_sdf\nusing docker file from issue <a href=\"#!/osrf/gzweb/issues/158/fail-to-add-model-from-database-gazebo9\" rel=\"nofollow\" title=\"Fail to add model from database gazebo9 + gzweb, gzweb9\" class=\"ap-connect-link\"><s>#158</s></a>\nand <a href=\"#!/osrf/gzweb/pull-requests/173/fix-inserting-models-from-insert-tab\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #173</a>\n<a href=\"#!/osrf/gzweb/pull-requests/173\" rel=\"nofollow\" class=\"ap-connect-link\">#!/osrf/gzweb/pull-requests/173</a></p>", "type": "rendered"}, "assignee": null, "state": "new", "version": null, "edited_on": null, "created_on": "2018-11-19T19:54:30.792124+00:00", "milestone": null, "updated_on": "2018-11-19T20:43:28.684263+00:00", "type": "issue", "id": 160}