{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "links": {"attachments": {"href": "data/repositories/osrf/gzweb/issues/41/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gzweb/issues/41.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/41/watch"}, "comments": {"href": "data/repositories/osrf/gzweb/issues/41/comments_page=1.json"}, "html": {"href": "#!/osrf/gzweb/issues/41/deploysh-errors-on-vmed-ubuntu-1204"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/41/vote"}}, "reporter": {"display_name": "Nick Sweet", "uuid": "{7148c918-f4ee-4696-9a93-ca3d4d5ed22c}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7148c918-f4ee-4696-9a93-ca3d4d5ed22c%7D"}, "html": {"href": "https://bitbucket.org/%7B7148c918-f4ee-4696-9a93-ca3d4d5ed22c%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/d0e268211e46eb31d9e39db0d8cffbcdd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsNS-1.png"}}, "nickname": "nckswt", "type": "user", "account_id": "557058:093cd9bd-573b-4137-8381-4e27226bb788"}, "title": "Deploy.sh errors on VM'ed Ubuntu 12.04", "component": null, "votes": 0, "watches": 2, "content": {"raw": "(Not sure if I should be adding this here or on http://answers.gazebosim.org/)\r\n\r\nWhen I run the `deploy.sh` script, I get a number of errors. Here's a selection of them (full output attached):\r\n\r\n\r\n```\r\n#!bash\r\n\r\nhome/cohrint/gzweb/tools/gzcoarse.cc: In function \u2018void ExportTextureSource(const gazebo::common::SubMesh*, const gazebo::common::SubMesh*, TiXmlElement*, const char*)\u2019:\r\n/home/cohrint/gzweb/tools/gzcoarse.cc:144:25: error: invalid conversion from \u2018long unsigned int*\u2019 to \u2018unsigned int*\u2019 [-fpermissive]\r\n/home/cohrint/gzweb/tools/nanoflann.hpp:947:21: error:   initializing argument 3 of \u2018void nanoflann::KDTreeSingleIndexAdaptor<Distance, DatasetAdaptor, DIM, IndexType>::knnSearch(const ElementType*, size_t, IndexType*, nanoflann::KDTreeSingleIndexAdaptor<Distance, DatasetAdaptor, DIM, IndexType>::DistanceType*, int) const [with Distance = nanoflann::L2_Simple_Adaptor<double, PointCloud<double> >, DatasetAdaptor = PointCloud<double>, int DIM = 3, IndexType = unsigned int, nanoflann::KDTreeSingleIndexAdaptor<Distance, DatasetAdaptor, DIM, IndexType>::ElementType = double, size_t = unsigned int, nanoflann::KDTreeSingleIndexAdaptor<Distance, DatasetAdaptor, DIM, IndexType>::DistanceType = double]\u2019 [-fpermissive]\r\nmake[2]: *** [tools/CMakeFiles/gzcoarse.dir/gzcoarse.cc.o] Error 1\r\nmake[1]: *** [tools/CMakeFiles/gzcoarse.dir/all] Error 2\r\nmake: *** [all] Error 2\r\n```\r\n\r\n\r\n```\r\n#!bash\r\n\r\nmake: Entering directory `/home/cohrint/gzweb/gzbridge/build'\r\n  CXX(target) Debug/obj.target/gzbridge/GZNode.o\r\ng++: fatal error: no input files\r\ncompilation terminated.\r\n/bin/sh: 1: /usr/include: Permission denied\r\nmake: *** [Debug/obj.target/gzbridge/GZNode.o] Error 126\r\nmake: Leaving directory `/home/cohrint/gzweb/gzbridge/build'\r\ngyp ERR! build error \r\ngyp ERR! stack Error: `make` failed with exit code: 2\r\ngyp ERR! stack     at ChildProcess.onExit (/home/cohrint/gzweb/node_modules/node-gyp/lib/build.js:267:23)\r\ngyp ERR! stack     at ChildProcess.emit (events.js:70:17)\r\ngyp ERR! stack     at maybeExit (child_process.js:360:16)\r\ngyp ERR! stack     at Process.onexit (child_process.js:396:5)\r\ngyp ERR! System Linux 3.2.0-60-generic-pae\r\ngyp ERR! command \"node\" \"/home/cohrint/gzweb/node_modules/.bin/node-gyp\" \"build\" \"-d\"\r\ngyp ERR! cwd /home/cohrint/gzweb/gzbridge\r\ngyp ERR! node -v v0.6.12\r\ngyp ERR! node-gyp -v v0.9.6\r\ngyp ERR! not ok \r\n\r\n```\r\n\r\n\r\n```\r\n#!bash\r\n\r\nerror [Errno 2] No such file or directory\r\nTraceback (most recent call last):\r\n  File \"./webify_models_v2.py\", line 44, in <module>\r\n    subprocess.check_call(cmd)\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 506, in check_call\r\n    retcode = call(*popenargs, **kwargs)\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 493, in call\r\n    return Popen(*popenargs, **kwargs).wait()\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 679, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 1249, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n```\r\n\r\n\r\nI'm running this on a VM of Ubuntu 12.04 from OS X on a late 2013 rMBP. Any idea what the issues might be caused by? This was built from the default branch, but I've also tried the 1.1.0 branch to the same outcome.", "markup": "markdown", "html": "<p>(Not sure if I should be adding this here or on <a href=\"http://answers.gazebosim.org/\" rel=\"nofollow\" class=\"ap-connect-link\">http://answers.gazebosim.org/</a>)</p>\n<p>When I run the <code>deploy.sh</code> script, I get a number of errors. Here's a selection of them (full output attached):</p>\n<div class=\"codehilite language-bash\"><pre><span></span>home/cohrint/gzweb/tools/gzcoarse.cc: In <span class=\"k\">function</span> \u2018void ExportTextureSource<span class=\"o\">(</span>const gazebo::common::SubMesh*, const gazebo::common::SubMesh*, TiXmlElement*, const char*<span class=\"o\">)</span>\u2019:\n/home/cohrint/gzweb/tools/gzcoarse.cc:144:25: error: invalid conversion from \u2018long unsigned int*\u2019 to \u2018unsigned int*\u2019 <span class=\"o\">[</span>-fpermissive<span class=\"o\">]</span>\n/home/cohrint/gzweb/tools/nanoflann.hpp:947:21: error:   initializing argument <span class=\"m\">3</span> of \u2018void nanoflann::KDTreeSingleIndexAdaptor&lt;Distance, DatasetAdaptor, DIM, IndexType&gt;::knnSearch<span class=\"o\">(</span>const ElementType*, size_t, IndexType*, nanoflann::KDTreeSingleIndexAdaptor&lt;Distance, DatasetAdaptor, DIM, IndexType&gt;::DistanceType*, int<span class=\"o\">)</span> const <span class=\"o\">[</span>with <span class=\"nv\">Distance</span> <span class=\"o\">=</span> nanoflann::L2_Simple_Adaptor&lt;double, PointCloud&lt;double&gt; &gt;, <span class=\"nv\">DatasetAdaptor</span> <span class=\"o\">=</span> PointCloud&lt;double&gt;, int <span class=\"nv\">DIM</span> <span class=\"o\">=</span> <span class=\"m\">3</span>, <span class=\"nv\">IndexType</span> <span class=\"o\">=</span> unsigned int, nanoflann::KDTreeSingleIndexAdaptor&lt;Distance, DatasetAdaptor, DIM, IndexType&gt;::ElementType <span class=\"o\">=</span> double, <span class=\"nv\">size_t</span> <span class=\"o\">=</span> unsigned int, nanoflann::KDTreeSingleIndexAdaptor&lt;Distance, DatasetAdaptor, DIM, IndexType&gt;::DistanceType <span class=\"o\">=</span> double<span class=\"o\">]</span>\u2019 <span class=\"o\">[</span>-fpermissive<span class=\"o\">]</span>\nmake<span class=\"o\">[</span><span class=\"m\">2</span><span class=\"o\">]</span>: *** <span class=\"o\">[</span>tools/CMakeFiles/gzcoarse.dir/gzcoarse.cc.o<span class=\"o\">]</span> Error <span class=\"m\">1</span>\nmake<span class=\"o\">[</span><span class=\"m\">1</span><span class=\"o\">]</span>: *** <span class=\"o\">[</span>tools/CMakeFiles/gzcoarse.dir/all<span class=\"o\">]</span> Error <span class=\"m\">2</span>\nmake: *** <span class=\"o\">[</span>all<span class=\"o\">]</span> Error <span class=\"m\">2</span>\n</pre></div>\n\n\n<div class=\"codehilite language-bash\"><pre><span></span>make: Entering directory <span class=\"sb\">`</span>/home/cohrint/gzweb/gzbridge/build<span class=\"s1\">&#39;</span>\n<span class=\"s1\">  CXX(target) Debug/obj.target/gzbridge/GZNode.o</span>\n<span class=\"s1\">g++: fatal error: no input files</span>\n<span class=\"s1\">compilation terminated.</span>\n<span class=\"s1\">/bin/sh: 1: /usr/include: Permission denied</span>\n<span class=\"s1\">make: *** [Debug/obj.target/gzbridge/GZNode.o] Error 126</span>\n<span class=\"s1\">make: Leaving directory `/home/cohrint/gzweb/gzbridge/build&#39;</span>\ngyp ERR! build error \ngyp ERR! stack Error: <span class=\"sb\">`</span>make<span class=\"sb\">`</span> failed with <span class=\"nb\">exit</span> code: <span class=\"m\">2</span>\ngyp ERR! stack     at ChildProcess.onExit <span class=\"o\">(</span>/home/cohrint/gzweb/node_modules/node-gyp/lib/build.js:267:23<span class=\"o\">)</span>\ngyp ERR! stack     at ChildProcess.emit <span class=\"o\">(</span>events.js:70:17<span class=\"o\">)</span>\ngyp ERR! stack     at maybeExit <span class=\"o\">(</span>child_process.js:360:16<span class=\"o\">)</span>\ngyp ERR! stack     at Process.onexit <span class=\"o\">(</span>child_process.js:396:5<span class=\"o\">)</span>\ngyp ERR! System Linux <span class=\"m\">3</span>.2.0-60-generic-pae\ngyp ERR! <span class=\"nb\">command</span> <span class=\"s2\">&quot;node&quot;</span> <span class=\"s2\">&quot;/home/cohrint/gzweb/node_modules/.bin/node-gyp&quot;</span> <span class=\"s2\">&quot;build&quot;</span> <span class=\"s2\">&quot;-d&quot;</span>\ngyp ERR! cwd /home/cohrint/gzweb/gzbridge\ngyp ERR! node -v v0.6.12\ngyp ERR! node-gyp -v v0.9.6\ngyp ERR! not ok \n</pre></div>\n\n\n<div class=\"codehilite language-bash\"><pre><span></span>error <span class=\"o\">[</span>Errno <span class=\"m\">2</span><span class=\"o\">]</span> No such file or directory\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;./webify_models_v2.py&quot;</span>, line <span class=\"m\">44</span>, in &lt;module&gt;\n    subprocess.check_call<span class=\"o\">(</span>cmd<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/usr/lib/python2.7/subprocess.py&quot;</span>, line <span class=\"m\">506</span>, in check_call\n    <span class=\"nv\">retcode</span> <span class=\"o\">=</span> call<span class=\"o\">(</span>*popenargs, **kwargs<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/usr/lib/python2.7/subprocess.py&quot;</span>, line <span class=\"m\">493</span>, in call\n    <span class=\"k\">return</span> Popen<span class=\"o\">(</span>*popenargs, **kwargs<span class=\"o\">)</span>.wait<span class=\"o\">()</span>\n  File <span class=\"s2\">&quot;/usr/lib/python2.7/subprocess.py&quot;</span>, line <span class=\"m\">679</span>, in __init__\n    errread, errwrite<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;/usr/lib/python2.7/subprocess.py&quot;</span>, line <span class=\"m\">1249</span>, in _execute_child\n    raise child_exception\nOSError: <span class=\"o\">[</span>Errno <span class=\"m\">2</span><span class=\"o\">]</span> No such file or directory\n</pre></div>\n\n\n<p>I'm running this on a VM of Ubuntu 12.04 from OS X on a late 2013 rMBP. Any idea what the issues might be caused by? This was built from the default branch, but I've also tried the 1.1.0 branch to the same outcome.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2014-08-12T22:36:23.163344+00:00", "milestone": null, "updated_on": "2014-08-29T05:27:32.494400+00:00", "type": "issue", "id": 41}